# Generated by Django 4.2.6 on 2023-11-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_code_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=0, verbose_name='Код верификации'),
        ),
    ]
